<?php

namespace AppBundle\Repository;

/**
 * TweetRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FavouriteRepository extends \Doctrine\ORM\EntityRepository
{


    public function getFavouritesByUserId($userId, $limit = 10)
    {
        $videos = $this->createQueryBuilder('f')
            ->add('select', 'f, u, t')
            ->add('from', 'AppBundle:User u')
            ->add('from', 'AppBundle:Tweet t')
            ->leftJoin('AppBundle:Comment', 'c')
            ->where('v.comment = c.id')
             ... // some other conditions if you need
             ->getQuery()
        ->getResult();


        return $this->createQueryBuilder('f')
            ->select('f')
            ->where('v.comment = c.id')
            ->orderBy('f.tweet.createdAt', 'DESC')
            //->orderBy('t.id', 'DESC')
            ->setMaxResults($limit)
            ->getQuery()
            ->getResult();
    }


}
