<?php

namespace AppBundle\Repository;

/**
 * TweetRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FavouriteRepository extends \Doctrine\ORM\EntityRepository
{


//    public function getFavouritesByUser($user, $limit = 10)
//    {
//        $favourites = $this->createQueryBuilder('f')
//            ->add('select', 'f, t')
//            ->add('from', 'AppBundle:Favourite f')
//            ->leftJoin('AppBundle:Tweet', 't')
//            ->add('where', 'f.tweet.id = t.id')
//            ->add('where', 'f.user = :user')
//            ->setParameter('user', $user)
//            //->orderBy('f.tweet.createdAt', 'DESC')
//            ->setMaxResults($limit)
//            ->getQuery()
//            ->getResult();
//
//        return $favourites;
//    }


    public function getFavouritesByUser($user, $limit = 10)
    {
        $favourites = $this->createQueryBuilder('f')
            ->add('select', 'f')
            ->add('from', 'AppBundle:Favourite f')
            ->add('where', 'f.user = :user')
            ->setParameter('user', $user)
            //->orderBy('f.tweet.createdAt', 'DESC')
            ->setMaxResults($limit)
            ->getQuery()
            ->getResult();

        return $favourites;
    }



    public function getFavouriteByUserAndTweet($user, $tweet)
    {
        $favourite = $this->createQueryBuilder('f')
            ->add('select', 'f')
            ->add('from', 'AppBundle:Favourite f')
            ->andWhere('f.user = :user')
            ->setParameter('user', $user)
            ->andWhere('f.tweet = :tweet')
            ->setParameter('tweet', $tweet)
            ->getQuery()
            ->getOneOrNullResult();

        return $favourite;
    }


}
